// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_kitchen__level_20 = "CgkI6fbRhMcNEAIQFA"; // <GPGSID>
        public const string leaderboard_kitchen__level_6 = "CgkI6fbRhMcNEAIQBg"; // <GPGSID>
        public const string leaderboard_kitchen__level_1 = "CgkI6fbRhMcNEAIQAQ"; // <GPGSID>
        public const string leaderboard_kitchen__level_3 = "CgkI6fbRhMcNEAIQAw"; // <GPGSID>
        public const string leaderboard_medieval__level_10 = "CgkI6fbRhMcNEAIQHg"; // <GPGSID>
        public const string leaderboard_kitchen__level_5 = "CgkI6fbRhMcNEAIQBQ"; // <GPGSID>
        public const string leaderboard_kitchen__level_4 = "CgkI6fbRhMcNEAIQBA"; // <GPGSID>
        public const string leaderboard_kitchen__level_7 = "CgkI6fbRhMcNEAIQBw"; // <GPGSID>
        public const string leaderboard_kitchen__level_9 = "CgkI6fbRhMcNEAIQCQ"; // <GPGSID>
        public const string leaderboard_kitchen__level_8 = "CgkI6fbRhMcNEAIQCA"; // <GPGSID>
        public const string leaderboard_medieval__level_1 = "CgkI6fbRhMcNEAIQFQ"; // <GPGSID>
        public const string leaderboard_medieval__level_3 = "CgkI6fbRhMcNEAIQFw"; // <GPGSID>
        public const string leaderboard_medieval__level_2 = "CgkI6fbRhMcNEAIQFg"; // <GPGSID>
        public const string leaderboard_medieval__level_5 = "CgkI6fbRhMcNEAIQGQ"; // <GPGSID>
        public const string leaderboard_medieval__level_4 = "CgkI6fbRhMcNEAIQGA"; // <GPGSID>
        public const string leaderboard_medieval__level_7 = "CgkI6fbRhMcNEAIQGw"; // <GPGSID>
        public const string leaderboard_medieval__level_6 = "CgkI6fbRhMcNEAIQGg"; // <GPGSID>
        public const string leaderboard_medieval__level_9 = "CgkI6fbRhMcNEAIQHQ"; // <GPGSID>
        public const string leaderboard_medieval__level_8 = "CgkI6fbRhMcNEAIQHA"; // <GPGSID>
        public const string leaderboard_kitchen__level_18 = "CgkI6fbRhMcNEAIQEg"; // <GPGSID>
        public const string leaderboard_kitchen__level_19 = "CgkI6fbRhMcNEAIQEw"; // <GPGSID>
        public const string leaderboard_kitchen__level_14 = "CgkI6fbRhMcNEAIQDg"; // <GPGSID>
        public const string leaderboard_kitchen__level_15 = "CgkI6fbRhMcNEAIQDw"; // <GPGSID>
        public const string leaderboard_kitchen__level_16 = "CgkI6fbRhMcNEAIQEA"; // <GPGSID>
        public const string leaderboard_kitchen__level_17 = "CgkI6fbRhMcNEAIQEQ"; // <GPGSID>
        public const string leaderboard_kitchen__level_10 = "CgkI6fbRhMcNEAIQCg"; // <GPGSID>
        public const string leaderboard_kitchen__level_11 = "CgkI6fbRhMcNEAIQCw"; // <GPGSID>
        public const string leaderboard_kitchen__level_12 = "CgkI6fbRhMcNEAIQDA"; // <GPGSID>
        public const string leaderboard_kitchen__level_13 = "CgkI6fbRhMcNEAIQDQ"; // <GPGSID>
        public const string leaderboard_alchemist__level_1 = "CgkI6fbRhMcNEAIQHw"; // <GPGSID>
        public const string leaderboard_kitchen__level_2 = "CgkI6fbRhMcNEAIQAg"; // <GPGSID>

}

